version: '3.8'

volumes:
 maria_vol:

networks:
  maria_net:
    driver: bridge
services:
  mariadb:
   image: mariadb:10.6.4
   restart: always
   container_name: mariadb
   ports:
    - 3306:3306
   networks:
    - maria_net
   volumes:
    #- mariadb_data:/mariadb
    - ~/MariaDb:/var/lib/mysql
   restart: always
   
   environment:
   # ALLOW_EMPTY_PASSWORD is recommended only for development.
     MARIADB_ROOT_PASSWORD: mariapwd
  phpmyadmin:
    image: phpmyadmin:5.0
    restart: always
    ports:
      - 8080:80
    networks:
      - maria_net
    depends_on:
      - mariadb
    environment:
      - PMA_ARBITRARY=1